name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: nodenv
        uses: nodenv/actions/node-version@main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}

      - uses: bahmutov/npm-install@v1

      - name: Run test
        run: npm run test
